name: PR check

on:
  pull_request:

jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run type

  unit:
    name: Unit Test
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: lts/krypton

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          cache-dependency-path: '**/bun.lock'

      - name: Install Bun
        run: bun install

      - name: Run Test
        run: bun run test

  e2e:
    name: Playwright
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: lts/krypton

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          cache-dependency-path: '**/bun.lock'

      - name: Install Bun
        run: bun install

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "version=$( node -e "console.log(require('@playwright/test/package.json').version)" )" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/ms-playwright
          key: "${{ runner.os }}-${{ runner.arch }}-playwright-chromium-${{ steps.playwright-version.outputs.version }}"
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-playwright-chromium-

      - name: Install Playwright browsers and system dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: bunx playwright install chromium --with-deps

      - name: Install Playwright system dependencies only
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: bunx playwright install-deps chromium

      - name: Run Playwright Tests
        run: bun run e2e

  build-web:
    name: Build web
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/krypton
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build:web
